openapi: 3.0.1
info:
  title: Account Service for Banking Micro-SOA System
  description: This is Account Service for Banking Micro-SOA System. Uses Apache CXF
    and Spring Boot on JAX-RS.
  contact:
    name: The Banking Micro-SOA System team
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://192.168.178.37:9080/services
paths:
  /api/account/{id}:
    get:
      description: getAccount
      operationId: getAccount_1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: Get Account by ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/AccountResponse"
        "404":
          description: Account whit this Id not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      description: addBankAccount
      operationId: addBankAccount_1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Bank Account to add
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddIdBankAccountRequest"
          application/xml:
            schema:
              $ref: "#/components/schemas/AddIdBankAccountRequest"
        required: true
      responses:
        default:
          description: Save Bank Account on Account
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/AccountResponse"
        "404":
          description: Account whit this Id not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/account/login:
    post:
      description: Authenticate user and return JWT
      operationId: login_1
      requestBody:
        description: Login
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCredentials"
          application/xml:
            schema:
              $ref: "#/components/schemas/UserCredentials"
        required: true
      responses:
        "200":
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/account/admin-account:
    post:
      description: openAccountAdmin
      operationId: openAccountAdmin_1
      requestBody:
        description: Account to be saved
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OpenBankAccountRequest"
          application/xml:
            schema:
              $ref: "#/components/schemas/OpenBankAccountRequest"
        required: true
      responses:
        "201":
          description: Save Admin Bank Account
          headers:
            Location:
              description: URL of the created resource
              style: simple
              schema:
                type: string
        "500":
          description: Account whit this Id not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/account/banker-account:
    post:
      description: openAccountBanker
      operationId: openAccountBanker_1
      requestBody:
        description: Account to be saved
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OpenBankAccountRequest"
          application/xml:
            schema:
              $ref: "#/components/schemas/OpenBankAccountRequest"
        required: true
      responses:
        "201":
          description: Save Banker Bank Account
          headers:
            Location:
              description: URL of the created resource
              style: simple
              schema:
                type: string
        "500":
          description: Account whit this Id not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/account/customer-account:
    post:
      description: openAccountCustomer
      operationId: openAccountCustomer_1
      requestBody:
        description: Account to be saved
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OpenBankAccountRequest"
          application/xml:
            schema:
              $ref: "#/components/schemas/OpenBankAccountRequest"
        required: true
      responses:
        "201":
          description: Save Customer Bank Account
          headers:
            Location:
              description: URL of the created resource
              style: simple
              schema:
                type: string
        "500":
          description: Account whit this Id not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    AccountResponse:
      required:
        - createDate
        - email
        - id
        - idBankAccount
        - name
        - phone
        - role
        - surname
        - updateDate
        - username
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        surname:
          type: string
        username:
          type: string
        email:
          type: string
        phone:
          type: string
        role:
          type: string
          enum:
            - ADMIN
            - BANKER
            - CUSTOMER
        idBankAccount:
          type: integer
          format: int64
        updateDate:
          type: string
          format: date-time
        createDate:
          type: string
          format: date-time
      xml:
        name: AccountResponse
    ErrorResponse:
      required:
        - error
      type: object
      properties:
        error:
          type: string
      xml:
        name: ErrorResponse
    AddIdBankAccountRequest:
      required:
        - idBankAccount
      type: object
      properties:
        idBankAccount:
          type: integer
          format: int64
      xml:
        name: AddIdBankAccountRequest
    TokenResponse:
      required:
        - token
      type: object
      properties:
        token:
          type: string
      xml:
        name: TokenResponse
    UserCredentials:
      required:
        - password
        - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      xml:
        name: UserCredentials
    OpenBankAccountRequest:
      required:
        - email
        - name
        - password
        - phone
        - surname
        - username
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        username:
          type: string
        password:
          type: string
        email:
          type: string
        phone:
          type: string
      xml:
        name: OpenBankAccountRequest
