spring.application:
  name: banking-service-client

application:
  version: @project.version@
---
spring:
  main:
    #    web-application-type: none
    banner-mode: console
    allow-bean-definition-overriding: true
  shell:
    interactive:
      enabled: true
---
logging:
  pattern:
    console:
---
gateway:
  base: host.docker.internal
  port: 9087
  paths:
    account: /api/account
    bankingOperation: /api/bank
    loan: /api/loan
    financialReport: /api/bank/financial-report
    transaction: /api/transaction

