spring.application:
  name: banking-service-client
---
spring:
  main:
    banner-mode: console
    allow-bean-definition-overriding: true
  shell:
    interactive:
      enabled: true
---
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:host.docker.internal}:${EUREKA_SERVER_PORT:8761}/eureka/
    fetchRegistry: true
---
jwt:
  token: your_jwt_token_here